### ISSUE TITLE
Depends on GLIBC >=2.16 while linux-anvil provides only 2.12

### ISSUE THREAD

**Issue by epruesse** [conda-forge/tensorflow-feedstock#67] opened 2019-04-18 15:29 UTC
The binaries repackaged by the current recipe depend on GLIBC 2.16. This leads to an error running tests in dependent packages using the plain `condaforge/linux-anvil` image:

```commandline
ImportError: /lib64/libc.so.6: version 'GLIBC_2.16' not found (required by 
/opt/conda/.../tensorflow/python/_pywrap_tensorflow_internal.so)
```
This issue would likely be fixed by #6 
This issue currently blocks https://github.com/bioconda/bioconda-recipes/pull/14499

**Comment by pgunn** [comment] 2019-04-30 22:32
This is also an issue for CentOS 7.x. I tried working around the issue by installing the same version of tensorflow from conda's defaults repo, although this forced a number of other unwanted package changes into my environment (most annoyingly, the defaults version of OpenCV, which was built without graphical support). A proper fix would be great.

**Comment by jakirkham** [comment] 2019-05-06 04:35
This is a duplicate of issue ( https://github.com/conda-forge/tensorflow-feedstock/issues/6 ). Going to go ahead and close. Please track and discuss in that issue instead. Thanks!

**Closed by jakirkham** 2019-05-06 04:35 UTC
