### ISSUE TITLE
Tensorflow install breaks (likely due to numpy)

### ISSUE THREAD

**Issue by mortonjt** [conda-forge/tensorflow-feedstock#64] opened 2018-11-18 06:36 UTC
Issue: Tensorflow seems to be breaking across multiple versions.

I'm trying to install tensorflow with another package, qiime2.  That install procedure is as follows

```
wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py35-osx-conda.yml
conda env create -q -n q2-dev --file qiime2-latest-py35-osx-conda.yml
source activate q2-dev
conda install tensorflow=1.5 -c conda-forge
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/mortonjt/miniconda3/envs/q2-dev:
#
# Name                    Version                   Build  Channel
absl-py                   0.5.0                      py_0    conda-forge
appnope                   0.1.0                    py35_0    conda-forge
arb-bio-tools             6.0.6                         4    bioconda
asn1crypto                0.24.0                   py35_3    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.weakref         1.0.post1                py35_0    conda-forge
bibtexparser              1.0.1                      py_1    conda-forge
bioconductor-biobase      2.38.0           r341h219a75b_1    bioconda
bioconductor-biocgenerics 0.24.0                   r341_1    bioconda
bioconductor-biocparallel 1.12.0           r341h219a75b_1    bioconda
bioconductor-biostrings   2.46.0                 r3.4.1_0    bioconda
bioconductor-dada2        1.6.0                  r3.4.1_0    bioconda
bioconductor-delayedarray 0.4.1                  r3.4.1_0    bioconda
bioconductor-genomeinfodb 1.14.0                 r3.4.1_0    bioconda
bioconductor-genomeinfodbdata 1.0.0                  r3.4.1_1    bioconda
bioconductor-genomicalignments 1.14.1                 r3.4.1_0    bioconda
bioconductor-genomicranges 1.30.3                 r3.4.1_0    bioconda
bioconductor-iranges      2.12.0                 r3.4.1_0    bioconda
bioconductor-rsamtools    1.30.0                 r3.4.1_0    bioconda
bioconductor-s4vectors    0.16.0                 r3.4.1_0    bioconda
bioconductor-shortread    1.36.0                 r3.4.1_0    bioconda
bioconductor-summarizedexperiment 1.8.0                  r3.4.1_0    bioconda
bioconductor-xvector      0.18.0                 r3.4.1_0    bioconda
bioconductor-zlibbioc     1.24.0                 r3.4.1_0    bioconda
biom-format               2.1.7            py35h7eb728f_0    conda-forge
blas                      1.0                         mkl  
blast                     2.6.0               boost1.64_2    bioconda
bleach                    1.5.0                    py35_0    conda-forge
bokeh                     0.13.0                   py35_0    conda-forge
boost                     1.67.0           py35h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cachecontrol              0.12.5                     py_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35h5e8e0c9_1    conda-forge
chardet                   3.0.4                    py35_3    conda-forge
click                     7.0                        py_0    conda-forge
cryptography              2.3.1            py35hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py35_0    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cutadapt                  1.18                     py35_0    bioconda
cycler                    0.10.0                     py_1    conda-forge
cython                    0.28.5           py35hfc679d8_0    conda-forge
deblur                    1.1.0                    py35_0    bioconda
decorator                 4.3.0                      py_0    conda-forge
emperor                   1.0.0beta18              py35_1    conda-forge
entrypoints               0.2.3                    py35_2    conda-forge
fastcluster               1.1.25           py35hf8a1672_0    conda-forge
fasttree                  2.1.10                        0    bioconda
fontconfig                2.13.1               hce039c3_0    conda-forge
fragment-insertion        4.3.5                    py35_0    biocore
freetype                  2.9.1                h6debe1e_4    conda-forge
future                    0.16.0                   py35_2    conda-forge
gettext                   0.19.8.1             h1f1d5ed_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gneiss                    0.4.4                      py_0    bioconda
graphite2                 1.3.12               h7d4d677_1    conda-forge
gsl                       2.1                           2    conda-forge
h5py                      2.7.0               np112py35_0    conda-forge
harfbuzz                  1.9.0                h08d66d9_0    conda-forge
hdf5                      1.8.17                       11    conda-forge
hdmedians                 0.13             py35h7eb728f_1    conda-forge
html5lib                  0.9999999                py35_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py35_2    conda-forge
ijson                     2.3                      py35_0    qiime2
intel-openmp              2019.0                      118  
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py35h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
iqtree                    1.6.8                he941832_0    bioconda
java-jdk                  8.0.92                        1    bioconda
jedi                      0.12.1                   py35_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libarbdb                  6.0.6                         4    bioconda
libcurl                   7.62.0               hbdb9355_0    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libprotobuf               3.6.0                hd28b015_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
mafft                     7.310                         1    bioconda
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0              py35h470a237_1    conda-forge
matplotlib                2.2.3            py35h0e0179f_0    conda-forge
mistune                   0.8.3            py35h470a237_2    conda-forge
mkl                       2019.0                      118  
msgpack-python            0.5.6            py35h2d50403_3    conda-forge
natsort                   5.4.0                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py35_2    conda-forge
notebook                  5.7.0                    py35_0    conda-forge
numpy                     1.12.1           py35h655160a_1  
openjdk                   8.0.152              h393ad39_1  
openmp                    7.0.0                h2d50403_0    conda-forge
openssl                   1.0.2p               h1de35cc_0  
packaging                 18.0                       py_0    conda-forge
pandas                    0.22.0                   py35_1    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
parso                     0.3.1                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.6.0                    py35_0    conda-forge
pickleshare               0.7.5                    py35_0    conda-forge
pigz                      2.3.4                         0    conda-forge
pip                       18.0                  py35_1001    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
prometheus_client         0.4.2                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.0            py35hfc679d8_0    conda-forge
psutil                    5.4.7            py35h470a237_1    conda-forge
ptyprocess                0.6.0                 py35_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pysocks                   1.6.8                    py35_2    conda-forge
python                    3.5.5                         1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyyaml                    3.13             py35h470a237_1    conda-forge
pyzmq                     17.1.2           py35hae99301_0    conda-forge
q2-alignment              2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-composition            2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-cutadapt               2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-dada2                  2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-deblur                 2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-demux                  2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-diversity              2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-emperor                2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-feature-classifier     2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-feature-table          2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-fragment-insertion     2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-gneiss                 2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-longitudinal           2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-metadata               2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-phylogeny              2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-quality-control        2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-quality-filter         2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-sample-classifier      2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-taxa                   2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-types                  2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2-vsearch                2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2cli                     2018.11.0                py35_0    qiime2-staging/label/r2018.11
q2templates               2018.11.0                py35_0    qiime2-staging/label/r2018.11
qiime2                    2018.11.0                py35_0    qiime2-staging/label/r2018.11
r-assertthat              0.2.0            r341h6115d3f_1    conda-forge
r-base                    3.4.1                         4    conda-forge
r-bh                      1.66.0_1              r341_1001    conda-forge
r-bitops                  1.0_6            r341hc070d10_2    conda-forge
r-cli                     1.0.0            r341h6115d3f_1    conda-forge
r-colorspace              1.3_2            r341hc070d10_2    conda-forge
r-crayon                  1.3.4            r341h6115d3f_1    conda-forge
r-data.table              1.11.4           r341hc070d10_2    conda-forge
r-digest                  0.6.18           r341hc070d10_0    conda-forge
r-fansi                   0.3.0            r341hc070d10_0    conda-forge
r-formatr                 1.5              r341h6115d3f_1    conda-forge
r-futile.logger           1.4.3            r341h6115d3f_1    conda-forge
r-futile.options          1.0.1            r341h6115d3f_0    conda-forge
r-ggplot2                 3.1.0            r341h6115d3f_0    conda-forge
r-glue                    1.3.0            r341h470a237_2    conda-forge
r-gtable                  0.2.0            r341h6115d3f_1    conda-forge
r-hwriter                 1.3.2            r341h6115d3f_1    conda-forge
r-labeling                0.3              r341h6115d3f_1    conda-forge
r-lambda.r                1.2.3            r341h6115d3f_0    conda-forge
r-lattice                 0.20_35          r341hc070d10_0    conda-forge
r-latticeextra            0.6_28           r341h6115d3f_1    conda-forge
r-lazyeval                0.2.1            r341hc070d10_2    conda-forge
r-magrittr                1.5              r341h6115d3f_1    conda-forge
r-mass                    7.3_50           r341hc070d10_2    conda-forge
r-matrix                  1.2_14           r341hc070d10_2    conda-forge
r-matrixstats             0.54.0           r341hc070d10_0    conda-forge
r-mgcv                    1.8_24           r341hc070d10_2    conda-forge
r-munsell                 0.5.0            r341h6115d3f_1    conda-forge
r-nlme                    3.1_137          r341h364d78e_0    conda-forge
r-pillar                  1.3.0            r341h6115d3f_0    conda-forge
r-plyr                    1.8.4            r341h9d2a408_2    conda-forge
r-r6                      2.2.2            r341h6115d3f_1    conda-forge
r-rcolorbrewer            1.1_2            r341h6115d3f_1    conda-forge
r-rcpp                    1.0.0            r341h9d2a408_0    conda-forge
r-rcppparallel            4.4.1            r341h9d2a408_0    conda-forge
r-rcurl                   1.95_4.11        r341hc070d10_3    conda-forge
r-reshape2                1.4.3            r341h9d2a408_2    conda-forge
r-rlang                   0.3.0.1          r341h470a237_0    conda-forge
r-scales                  1.0.0            r341h9d2a408_1    conda-forge
r-snow                    0.4_3            r341h6115d3f_0    conda-forge
r-stringi                 1.2.4            r341h9d2a408_1    conda-forge
r-stringr                 1.3.1            r341h6115d3f_1    conda-forge
r-tibble                  1.4.2            r341hc070d10_2    conda-forge
r-utf8                    1.1.4            r341hc070d10_0    conda-forge
r-viridislite             0.3.0            r341h6115d3f_1    conda-forge
r-withr                   2.1.2            r341h6115d3f_0    conda-forge
raxml                     8.2.12               h470a237_0    bioconda
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py35_1    conda-forge
scikit-bio                0.5.4                    py35_0    conda-forge
scikit-learn              0.19.1           py35h2b554eb_0  
scipy                     0.19.1           py35hf362045_3  
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sina                      1.4.0                h4ef8376_0    bioconda
six                       1.11.0                   py35_1  
sortmerna                 2.0                  he941832_3    bioconda
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.9.0                    py35_0    conda-forge
tbb                       2019.2               h2d50403_0    conda-forge
tensorboard               1.5.1                    py35_1    conda-forge
tensorflow                1.5.1                    py35_0    conda-forge
terminado                 0.8.1                    py35_1    conda-forge
testpath                  0.3.1                    py35_1    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
tornado                   5.1.1            py35h470a237_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
tzlocal                   1.3                      py35_0    qiime2
unifrac                   0.9.2            py35h1806a49_1    biocore
urllib3                   1.23                     py35_1    conda-forge
vsearch                   2.7.0                         1    bioconda
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wget                      1.19.5               hf30b1f0_0  
wheel                     0.32.0                py35_1000    conda-forge
widgetsnbextension        3.4.2                    py35_0    conda-forge
xopen                     0.3.5                      py_0    bioconda
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : q2-dev
    active env location : /Users/mortonjt/miniconda3/envs/q2-dev
            shell level : 1
       user config file : /Users/mortonjt/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /Users/mortonjt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/mortonjt/miniconda3/pkgs
                          /Users/mortonjt/.conda/pkgs
       envs directories : /Users/mortonjt/miniconda3/envs
                          /Users/mortonjt/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

I'm trying to conda install tensorflow=1.5 and get the following error when importing in python

```
python -c "import tensorflow"
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-11-17 22:23:17.984293: F tensorflow/python/lib/core/bfloat16.cc:664] Check failed: PyBfloat16_Type.tp_base != nullptr 
Abort trap: 6
```

Has anyone else noticed these sorts of errors?  Not entirely sure why this is the case, especially since numpy=1.12 should be compatible.

I then tried to see if I could install tensorflow by itself, and still had issues.

```
conda create -n tf-test tensorflow -c conda-forge
source activate tf-test
python -c "import tensorflow"

Traceback (most recent call last):
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so (which was built for Mac OS X 10.12)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so (which was built for Mac OS X 10.12)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/mortonjt/miniconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Below are the environment details for the 2nd attempt

<br/>

Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/mortonjt/miniconda3/envs/tf-test:
#
# Name                    Version                   Build  Channel
absl-py                   0.6.1                 py36_1000    conda-forge
astor                     0.7.1                      py_0    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.6                         1    conda-forge
c-ares                    1.15.0               h470a237_1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
gast                      0.2.0                      py_0    conda-forge
grpcio                    1.16.0           py36hd60e7a3_0    conda-forge
intel-openmp              2019.0                      118  
libffi                    3.2.1                hfc679d8_5    conda-forge
libgfortran               3.0.1                h93005f0_2  
libprotobuf               3.6.1                hd28b015_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.15.4           py36h6a91979_0  
numpy-base                1.15.4           py36h8a80b8c_0  
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
protobuf                  3.6.1            py36hfc679d8_1    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tensorboard               1.10.0                   py36_0    conda-forge
tensorflow                1.10.0                   py36_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

</details>

Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : tf-test
    active env location : /Users/mortonjt/miniconda3/envs/tf-test
            shell level : 1
       user config file : /Users/mortonjt/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /Users/mortonjt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/mortonjt/miniconda3/pkgs
                          /Users/mortonjt/.conda/pkgs
       envs directories : /Users/mortonjt/miniconda3/envs
                          /Users/mortonjt/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

Any insights will be greatly appreciated!  And this resource is extremely useful, particularly for tools that heavily rely on the conda build!

**Comment by jjhelmus** [comment] 2018-11-19 03:18
Can you upgrade the numpy package in the first environment to 1.13 or newer?  There were some issues with the Tensorflow 1.5.1 wheels requiring a newer NumPy version than the requirements expressed, cf tensorflow/tensorflow#16488, which were copied into the conda package.  Upgrading NumPy usually fixes the issue.

The later issue I believe is caused by the minimum version of macOS being 10.12 for Tensorflow 1.10.0.

**Comment by mortonjt** [comment] 2018-11-19 04:39
Makes sense.  Thanks!
 
At the moment, qiime2 is fixed at numpy=1.12 -- but we are currently in discussion about bumping up the numpy version there.

That being said, I was still having issues with the standalone TF installation with conda-forge (even without specifying the numpy version or other qiime2 dependencies).
The anaconda version seems to be working though via

```
conda create -n tf-test2 tensorflow -c anaconda
source activate tf-test2
python -c "import tensorflow as tf; print(tf.__version__)" 
'1.12.0'
```

**Comment by jjhelmus** [comment] 2018-11-19 07:32
The anaconda package (but please use `defaults` not `anaconda`) is built from source and will work with macOS 10.11 and above.  The `conda-forge` package is a repackage of the wheels provided by Google, which appear to support macOS 10.12 and above.  Building Tensorflow from source, see #6, could solve this problem but is quite challenging.

**Comment by hmaarrfk** [comment] 2021-10-31 22:15
I believe this has been addressed in recent versions.

i would suggest adding a tensorflow pinning `>=2.6`. should help with these builds.

**Comment by h-vetinari** [comment] 2021-11-22 11:24
Yeah, this is an ancient issue, let's close it (but please feel free to open a new one if there are any remaining problems!)

**Closed by h-vetinari** 2021-11-22 11:24 UTC
