### ISSUE TITLE
Remove unnecessary dep on glibc newer than 2.17?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [conda-forge/tensorflow-feedstock#224] opened 2022-04-29 20:26 UTC
### Comment:

Not sure, but it appears that the latest tensorflow packages may depend on glibc newer than 2.17.

The example below shows the conflict.  If I use "2.6" instead of "2.7", it installs, giving "tensorflow-2.6.2-cuda112py39h9333c2f_1".

It could be that tensorflow truly needs a newer glibc.  I have a suspicion, though, that it doesn't and is simply picking up the version of glibc on the system where the package is being compiled.  (I'm pretty fuzzy on how this works.)

Unfortunately, we're on RHEL 7 in a HPC environment, and upgrading glibc won't be possible anytime soon.  If this theory is correct, would it be possible to build these packages with a somewhat older glibc?

```
$ conda create -q -n xxx --override-channels -c conda-forge -c defaults 'tensorflow>=2.7=cuda11*'
...
Found conflicts! Looking for incompatible packages.
...
UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - tensorflow[version='>=2.7',build=cuda11*] -> __cuda

Your installed version is: 2.17
```

**Comment by izahn** [comment] 2022-04-29 20:55
Hmm, that error looks pretty weird. Centos 7 has `glibc 2.17` and your error message even says
> Your installed version is: 2.17

I think the actual problem is the last entry in the error message list, i.e., you try to install a CUDA-enabled build on a system without a GPU. see https://conda-forge.org/docs/user/tipsandtricks.html#installing-cuda-enabled-packages-like-tensorflow-and-pytorch for a work-around, i.e., 
```
CONDA_OVERRIDE_CUDA="11.2" conda create -q -n xxx --override-channels -c conda-forge 'tensorflow>=2.7=cuda11*'
```

**Comment by njzjz** [comment] 2022-04-29 20:59
No, your message is actually caused by CUDA. See #216.

**Comment by ngam** [comment] 2022-04-29 21:35
Also related: #208 #222

**Comment by michaelkarlcoleman** [comment] 2022-05-02 19:52
Thanks for everyone's help.  Feeling slightly sheepish that I didn't figure that on my own.  In my defense, that red herring about our glibc version is quite misleading.

In an HPC environment, any attempt to notice GPU hardware that is or is not present is pretty much doomed.  We have a variety of cards, sometimes multiple architectures on the same host.  And with new hot-plug (e.g., Liqid) hardware coming, any given node can rapidly have different kinds of GPUs added and removed.

I understand that that's not the typical case for most users.  It would be handy, though, if there were some sort of clearer diagnostic that amounted to "I tried to guess your GPU, I don't see any, and I'm going to refuse to install, even though you explicitly asked for build `cuda11*`".

**Comment by njzjz** [comment] 2022-05-02 21:15
I think you need to report or contribute to the [conda/conda](https://github.com/conda/conda) repo. The source code of this message is [here](https://github.com/conda/conda/blob/897384a046191eeebc2b9cb32a574dc87573a73c/conda/exceptions.py?q=The+following+specifications+were+found+to+be+incompatible#L709-L714).

**Comment by hmaarrfk** [comment] 2022-05-02 22:59
I think the ask would be that when a constraint on a virtual package is raised, that it raises a more human understandable message.

**Comment by ngam** [comment] 2022-05-03 16:24
> In an HPC environment, any attempt to notice GPU hardware that is or is not present is pretty much doomed. We have a variety of cards, sometimes multiple architectures on the same host. And with new hot-plug (e.g., Liqid) hardware coming, any given node can rapidly have different kinds of GPUs added and removed.

Surprised you got internet connection on the compute nodes with the GPUs! I've never had access to compute nodes with internet access :/

> I understand that that's not the typical case for most users. It would be handy, though, if there were some sort of clearer diagnostic that amounted to "I tried to guess your GPU, I don't see any, and I'm going to refuse to install, even though you explicitly asked for build cuda11*".

I was initially against the change that led to this strictness, but I was told it was for the better in general and the community (especially the maintainers here) seem to agree. I still am worried about other downstream effects of this change (i.e. people who work in containers and deploying to hubs, etc.). But I guess, we will see how things develop...

So your feedback is extremely valuable!


> I think the ask would be that when a constraint on a virtual package is raised, that it raises a more human understandable message.

Yes! You always come up with the neatest solutions 😅

I also think we, at conda-forge, need to adopt an ecosystem-wide implementation/policy for this — not many other packages implement the `__cuda` runtime constraint as far I could tell and so, even with better documentation and error messages, this strictness will remain confusing because if one could install (as an example) cuda-enabled pytorch on a cpu-only machine, but not the cuda-enabled tensorflow, I don't think any level of documentation can clarify that...

**Comment by michaelkarlcoleman** [comment] 2022-05-03 21:37
> I think you need to report or contribute to the [conda/conda](https://github.com/conda/conda) repo. The source code of this message is [here](https://github.com/conda/conda/blob/897384a046191eeebc2b9cb32a574dc87573a73c/conda/exceptions.py?q=The+following+specifications+were+found+to+be+incompatible#L709-L714).

This sounds right.  I'm going to pass, partly due to lack of time, but mostly because I don't think I understand the issues and mechanism well enough to file a useful report or suggestion.  I'd be happy to have someone else take a stab.

**Comment by hmaarrfk** [comment] 2022-05-04 02:18
Sounds fair.

In that case, i'm going to close this issue.

**Closed by hmaarrfk** 2022-05-04 02:18 UTC
Labels: question
