### ISSUE TITLE
tensorflow warning compile time version vs runtime version

### ISSUE THREAD

**Issue by peterjc** [conda-forge/tensorflow-feedstock#49] opened 2018-01-31 15:09 UTC
As part of testing a larger codebase using tensorflow, I get the following warning: ``RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)``

This is easy to reproduce using the conda provided Python, tensorflow, h5py, etc:

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
/mnt/shared/scratch/xxx/xxx/apps/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/mnt/shared/scratch/xxx/xxx/apps/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
1.4.0
```

The warning from h5py is separate and probably harmless (about a planned NumPy change):

```
$ python -c "import h5py"
/mnt/shared/scratch/xxx/xxx/apps/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

```

Using 64-bit Linux,

```
$ uname -a
Linux XXX 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.6.3
$ conda --version
conda 4.3.33
$ conda list h5py
# packages in environment at /mnt/shared/scratch/xxx/xxx/apps/conda:
#
h5py                      2.7.1                    py36_2    conda-forge
$ conda list tensorflow
# packages in environment at /mnt/shared/scratch/xxx/xxx/apps/conda:
#
tensorflow                1.4.0                    py36_0    conda-forge
```

**Comment by peterjc** [comment] 2018-01-31 15:11
FYI: There's an open issue with a pending pull request to fix the warning in ``h5py``,
https://github.com/h5py/h5py/issues/961

**Comment by jakirkham** [comment] 2018-01-31 15:38
Indeed, this is a known `h5py` issue caused by changes in `numpy` 1.14. The warning should go away when using `numpy` 1.13.

Given this, I'm not sure we can do anything at the `tensorflow` package level. Any suggestions or should we close and follow the `h5py` issue?

**Comment by peterjc** [comment] 2018-01-31 15:42
The ``h5py`` / ``numpy`` 1.14 issue is a minor distraction, its not a packaging issue that I think we need to worry about.

Do you understand what the ``tensorflow`` warning is about?

**Comment by jakirkham** [comment] 2018-01-31 16:16
Ah ok. Missed that on first pass. Guessing you are referring to this?

```python
RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
```

Looks like issue ( https://github.com/tensorflow/tensorflow/issues/14273 ) and ( https://github.com/tensorflow/tensorflow/issues/14182 ) is relevant. Sounds like something was off about the Python 3.6 build of 1.4.0. There was a 1.5.0 release made, which presumably fixes the problem (as noted in the last issue).

Would you like to send a PR to upgrade the feedstock to 1.5.0?

**Comment by peterjc** [comment] 2018-01-31 17:01
That's good news. I can try updating the recipe to build tensorflow 1.5.0 tomorrow afternoon. If anyone wants to try this before then, please go ahead.

**Comment by jjhelmus** [comment] 2018-02-01 14:25
From what I recall Google builds a single Python 3 tensorflow wheel and then packages it for Python 3.5 and 3.6.  This more-or-less works because Python 3 has a [stable ABI](https://docs.python.org/3/c-api/stable.html) but it does result in these warnings.  Building tensorflow from source against both Python 3.5 and 3.6 will remove this warning.  For `defaults` the [tensorflow-base](https://github.com/AnacondaRecipes/aggregate/tree/master/tensorflow-base-feedstock/recipe) recipe is used for the linux-64 build.

**Comment by peterjc** [comment] 2018-02-01 14:54
So while updating to v1.5.0 might be useful, switching to compiling under Linux may be needed (i.e. #12)?

**Comment by jakirkham** [comment] 2018-02-01 20:03
My understanding is the new version was built for Python 3.6 as opposed to converting the Python 3.5 one.

Am not opposed to building from source. It’s been challenging to do in practice. However if someone has time and bandwidth, please feel free to explore.

**Comment by hmaarrfk** [comment] 2021-10-31 22:13
is it ok to close this issue? i think this issue no longer applies in 2021

**Comment by peterjc** [comment] 2021-11-01 09:39
I have no objection to closing this issue - but have not tried to use tensorflow lately.

**Comment by jakirkham** [comment] 2021-11-01 10:16
If it shows up again, we can always reopen or track in a fresh issue 🙂

**Closed** 2021-11-01 10:15 UTC
